# 端口号配置
server:
  port: 8085

spring:
  # jdbc配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/platform?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
    url: jdbc:mysql://116.62.149.187:3306/platform?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678
#    url: jdbc:mysql://121.4.230.215:3306/platform?serverTimezone=GMT%2B8&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456

    driver-class-name: com.mysql.cj.jdbc.Driver
    #druit
#    druid:
#      enable: true
#      initial-size: 5
#      max-active: 20
#      min-idle: 5
#      max-wait: 60000
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filter:
#        stat:
#          merge-sql: true
  #redis
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password:
#    timeout: 10000
#    pool:
#      max-active: 8
#      max-idle: 8
#      max-wait: -1
#      min-idle: 0

mybatis:
  #映射文件路径
  mapper-locations: classpath:mappers/*.xml
  #模型所在的包名
  type-aliases-package: com.star.platforms

#log
logging:
  config: classpath:log4j2-spring.xml